<?php

namespace ContainerXL4MXqV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BruONDFService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.BruONDF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BruONDF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'book' => ['privates', '.errored..service_locator.BruONDF.App\\Entity\\Manufacturer', NULL, 'Cannot autowire service ".service_locator.BruONDF": it references class "App\\Entity\\Manufacturer" but no such service exists.'],
        ], [
            'book' => 'App\\Entity\\Manufacturer',
        ]);
    }
}
