<?php

namespace ContainerXL4MXqV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getManufacturer3Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IQtEzWo.App\Entity\Manufacturer' shared service.
     *
     * @return \App\Entity\Manufacturer
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.IQtEzWo": it references class "App\\Entity\\Manufacturer" but no such service exists.');
    }
}
