<?php

namespace ContainerXL4MXqV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getManufacturerControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\ManufacturerController' shared autowired service.
     *
     * @return \App\Controller\ManufacturerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ManufacturerController.php';

        $container->services['App\\Controller\\ManufacturerController'] = $instance = new \App\Controller\ManufacturerController();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\ManufacturerController', $container));

        return $instance;
    }
}
