<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXL4MXqV\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXL4MXqV/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXL4MXqV.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerXL4MXqV\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerXL4MXqV\App_KernelTestDebugContainer([
    'container.build_hash' => 'XL4MXqV',
    'container.build_id' => 'c1e10727',
    'container.build_time' => 1669617103,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXL4MXqV');
