<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWtIKcg3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWtIKcg3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWtIKcg3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWtIKcg3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWtIKcg3\App_KernelDevDebugContainer([
    'container.build_hash' => 'WtIKcg3',
    'container.build_id' => 'e4018e7e',
    'container.build_time' => 1669901684,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWtIKcg3');
